### ISSUE TITLE
希望提供 JitPack 等包的形式，以及希望降低 minSDK 版本

### ISSUE THREAD

**Issue by Moriafly** [xiaowine/LyricGetterApi#4]

**Comment by xiaowine** [comment]
能力有限， JitPack等包的形式还不会，如果可以的话，你可以帮帮忙
minSDK我给降到了21

**Comment by xiaowine** [comment]
照着你的库学习了下
[JitPack包](https://github.com/xiaowine/Lyric-Getter-Api)

**Comment by Moriafly** [comment]
收到辛苦了

**Comment by xiaowine** [comment]
> 收到辛苦了

如果对api有任何见解，都可以说
